### ISSUE TITLE
Discussion: Add support for OQT-API

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-py#87]
Would it be possible AND useful to add support for the OQT-API to this client. Currently I see the main strengths of this client in the 

1. input transformation
2. error handling
3. result2pandas parsing

**Comment by matthiasschaub** [comment]
After in-group discussion we decided not to add support for the OQT-API. 

Reasons are among others: 
- This would likely lead to confusion on the user side.
- Requests to the OQT-API are quite simple in-itself.
- The error handling of the OQT-API has to be improved by OQT and not through another client.

If additional features such as input geometry transformation or result2pandas parsing are needed when making requests to the OQT-API it make sense to write a new python package (oqt client) instead of integrating it into ohsome-py.

This issue can therefore be closed (It looks like I do not have the rights to close)
